main: com.sereneoasis.SereneWorldGen
name: SereneWorldGen
author: Sujan
version: 1.0.0
api-version: '1.20'
load: STARTUP
commands:
  SereneWorldGen:
    description: Your description
    usage: /<command>